import pathlib

#%% define the directories
# Define root path
root_path = pathlib.Path(__file__).resolve().parents[1]
# Define raw data path
data_raw_path = root_path.joinpath('data')
results_path = root_path.joinpath('results')
logging_path = root_path.joinpath('logging')

# Construct the config dictionary
config = {
    'root_path': root_path,
    'data_path': {
        'base': data_raw_path,
        'asq': data_raw_path.joinpath('asq'),
        'students': data_raw_path.joinpath('class_students'),
        'dataset_students': data_raw_path.joinpath('dataset_students.csv'),
        'calendar': data_raw_path.joinpath('calendar.xlsx'),
        'pp_dataset': data_raw_path.joinpath('pproc').joinpath('asq_pair.csv'),
        'asq_dictionary': data_raw_path.joinpath('asq_dictionary_v4.xlsx'),
    },
    'results_path': results_path,
    'logging_path': logging_path,
}

aliases = {
    'dem_0110': 'Age',
    'dem_0500': 'Sex At Birth',
    'dem_0800': 'BMI',
    'dem_1000': 'Racial Category',
    'map_0300': 'Snorting Gasping',
    'osa_0200': 'Perspire heavily during the night',
    'ess_0900': 'ESS Score',
    'isi_0100': 'Difficulty falling asleep',
    'isi_0200': 'Difficulty staying asleep',
    'isi_0300': 'Problem waking up too early',
    'cir_0200': 'What time of day would you get up',
    'fosq_0100': 'Difficulty concentrating',
    'fosq_0200': 'Difficulty remembering',
    'gad_0900': 'GAD-2 Score',
    'phq_1100': 'PHQ-2 Score',
    'fosq_1100': 'FOSQ Score',
    'isi_score': 'ISI Score',
    'soclhx_0500': 'Exercise per week',
    # columns that will not be used for the statistical significance
    'sched_total_sleep_time_week': 'Total Sleep Time Week',
    'sched_total_sleep_time_weekend': 'Total Sleep Time Weekend',
    'sched_total_sleep_latency_week': 'Total Sleep Latency Week',
    'sched_total_sleep_latency_weekend': 'Total Sleep Time Weekend',
    # 'sched_bed_time_week_diff': 'Bed Time Week Difference',
    # 'sched_bed_time_weekend_diff': 'Bed Time Weekend Difference',
    'mdhx_sleep_diagnosis_1': 'Previous Diagnosis of Sleep Apnea',
    'mdhx_sleep_diagnosis_2': 'Previous Diagnosis of Insomnia',
    'mdhx_sleep_diagnosis_3': 'Previous Diagnosis of Circadian Rhythm Disturbance',
    'mdhx_sleep_diagnosis_4': 'Previous Diagnosis of RLS/PLM',
    'mdhx_sleep_diagnosis_5': 'Previous Diagnosis of Narcolepsy',
    'mdhx_sleep_diagnosis_6': 'Previous Diagnosis of RBD',
    'mdhx_sleep_diagnosis_7': 'Previous Diagnosis of Sleepwalking',
    'mdhx_sleep_diagnosis_9': 'Previous Diagnosis of Hypersomnia',
    'mdhx_sleep_problem_1': 'Primary Complaint(s) (Sleep Problem) Snoring',
    'mdhx_sleep_problem_2': 'Primary Complaint(s) (Sleep Problem) My breathing stops at nighttime',
    'mdhx_sleep_problem_3': 'Primary Complaint(s) (Sleep Problem) Sleepiness during the day',
    'mdhx_sleep_problem_4': 'Primary Complaint(s) (Sleep Problem) Unrefreshing sleep',
    'mdhx_sleep_problem_5': 'Primary Complaint(s) (Sleep Problem) Difficulty falling asleep',
    'mdhx_sleep_problem_6': 'Primary Complaint(s) (Sleep Problem) Difficulty staying asleep',
    'mdhx_sleep_problem_7': 'Primary Complaint(s) (Sleep Problem) Difficulty keeping a normal sleep schedule',
    'mdhx_sleep_problem_8': 'Primary Complaint(s) (Sleep Problem) Talk, walk, and/or other behavior in sleep',
    'mdhx_sleep_problem_9': 'Primary Complaint(s) (Sleep Problem) Nightmares',
    'mdhx_sleep_problem_10': 'Primary Complaint(s) (Sleep Problem) Act out dreams',
    'mdhx_sleep_problem_11': 'Primary Complaint(s) (Sleep Problem) Restless legs or unpleasant sensations in legs',
    'mdhx_sleep_problem_12': 'Primary Complaint(s) (Sleep Problem) Weakness in muscles when surprised',
    'mdhx_sleep_problem_14': 'Primary Complaint(s) (Sleep Problem) Other',  # duplicated
}

dtypes = {
    'dem_0110': 'continuous',
    'dem_0500': 'binary',
    'dem_0800': 'continuous',
    'dem_1000': 'categorical',
    'map_0300': 'ordinal',
    'osa_0200': 'ordinal',
    'ess_0900': 'continuous',
    'isi_0100': 'ordinal',
    'isi_0200': 'ordinal',
    'isi_0300': 'ordinal',
    'cir_0200': 'categorical',
    'fosq_0100': 'ordinal',
    'fosq_0200': 'ordinal',
    'gad_0900': 'continuous',
    'phq_1100': 'continuous',
    'fosq_1100': 'continuous',
    'isi_score': 'continuous',
    'soclhx_0500': 'continuous',
    'sched_total_sleep_time_week': 'continuous',
    'sched_total_sleep_time_weekend': 'continuous',
    'sched_total_sleep_latency_week': 'continuous',
    'sched_total_sleep_latency_weekend': 'continuous',
    # 'sched_bed_time_week_diff': 'continuous',
    # 'sched_bed_time_weekend_diff': 'continuous',
    'mdhx_sleep_diagnosis_1': 'binary',
    'mdhx_sleep_diagnosis_2': 'binary',
    'mdhx_sleep_diagnosis_3': 'binary',
    'mdhx_sleep_diagnosis_4': 'binary',
    'mdhx_sleep_diagnosis_5': 'binary',
    'mdhx_sleep_diagnosis_6': 'binary',
    'mdhx_sleep_diagnosis_7': 'binary',
    'mdhx_sleep_diagnosis_9': 'binary',
    'mdhx_sleep_problem_1': 'binary',
    'mdhx_sleep_problem_2': 'binary',
    'mdhx_sleep_problem_3': 'binary',
    'mdhx_sleep_problem_4': 'binary',
    'mdhx_sleep_problem_5': 'binary',
    'mdhx_sleep_problem_6': 'binary',
    'mdhx_sleep_problem_7': 'binary',
    'mdhx_sleep_problem_8': 'binary',
    'mdhx_sleep_problem_9': 'binary',
    'mdhx_sleep_problem_10': 'binary',
    'mdhx_sleep_problem_11': 'binary',
    'mdhx_sleep_problem_12': 'binary',
    'mdhx_sleep_problem_14': 'binary',
}
